"""rename department

Revision ID: 019245829b30
Revises: d1b68656339d
Create Date: 2024-06-19 19:17:21.821331

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '019245829b30'
down_revision = 'd1b68656339d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('department', 'departments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('departments', 'department')
    # ### end Alembic commands ###
